inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Bundler:
  Enabled: true
Gemspec:
  Enabled: true
Layout:
  Enabled: true
Lint:
  Enabled: true
Naming:
  Enabled: true
Performance:
  Enabled: true
Rails:
  Enabled: true
Security:
  Enabled: true
